project: consumer

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
  banner:
    charset: UTF-8
  mvc:
    view:
      prefix: /static/
    static-path-pattern: /static/**
    show-sql: false
#  dubbo:
#    application:
#      name: ccc
#    registry:
#      address: zookeeper://127.0.0.1:2181
#    protocol:
#      name: dubbo
#      port: 20880
#    scan: com.steer.dubbo.consumer.service


server:
  port: 8088
  servlet:
    context-path: /${project}
  tomcat:
    uri-encoding: utf-8
